theme: jekyll-theme-architect
title: UCG-GFRD Technique
author: Sriramvignesh Mani
email: m.sriramvignesh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A combined particle and mesoscale technique for simulating reactive-diffusive systems
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  srmani # DO NOT include the @ character, or else the build will fail!
show_excerpts: true # set to false to remove excerpts on the homepage